Add Hilt gradle
teamtuna/leechunbok pull request #55
Opened 2023-05-31 14:57 UTC by csi111

hilt.gralde을 apply 시키면 바로 쓸 수 있게 추가했어요.

2023-05-31 14:58 UTC, pennya submitted a review, later dismissed
GOOD!

2023-05-31 14:59 UTC, babosamo approved these changes, later dismissed

2023-05-31 15:00 UTC, eastar-dev commented on gradle/libs.versions.toml
> +hilt = "2.46.1"
버전이 추가 되어 있는곳과 다릅니다. 
    id("com.google.dagger.hilt.android") version "2.45" apply false
  해당 부분도 같이 버전을 변경 해야 할듣 합니다.

2023-05-31 15:01 UTC, eastar-dev requested changes
hilt 버전도 toml 쪽으로 통일하기를 원합니다.

2023-05-31 15:05 UTC, eastar-dev commented on gradle/libs.versions.toml
> +hilt = "2.46.1"
아래 정도에 플러그 인이 있으면 될듣 합니다.


```
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
```

2023-05-31 15:15 UTC, karrel84 approved these changes, later dismissed

2023-05-31 15:21 UTC, eastar-dev commented on gradle/libs.versions.toml
```suggestion
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
```

2023-05-31 17:22 UTC, csi111 commented on gradle/libs.versions.toml
> +hilt = "2.46.1"
https://github.com/teamtuna/leechunbok/pull/55/commits/521f7d0da62516b5eebd53ea13730897e5dea509
우선은 application이랑 hilt만 넣어뒀어요 나머진 다른 PR로!!!

2023-05-31 17:22 UTC, csi111 commented on gradle/libs.versions.toml
여기도 반영해뒀어요
https://github.com/teamtuna/leechunbok/pull/55/commits/521f7d0da62516b5eebd53ea13730897e5dea509

2023-06-07 13:05 UTC, pennya approved these changes

2023-06-07 13:08 UTC, babosamo approved these changes

2023-06-07 13:54 UTC, karrel84 approved these changes

2023-06-07 13:55 UTC, eastar-dev approved these changes
LGTM

2023-06-07 13:56 UTC, merged